@views/feed.sql
@views/grades.sql
@views/my_data.sql
@views/my_draft.sql
@views/my_messages.sql
@views/rank_post.sql
@views/sanctions.sql
@views/tendance.sql
@views/top_user.sql
@views/urgent_signal.sql
@views/user_ranks.sql